services:
  spring-app:
    image: backend-projects:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/projects
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: my_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin 
      MYSQL_DATABASE: projects
      MYSQL_PASSWORD: admin      
    ports:
      - "3306:3306"            
    volumes:
      - mysql_data:/var/lib/mysql  

volumes:
  mysql_data:
    driver: local